# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 100, 111, 16))
        font = QtGui.QFont()
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.joinButton = QtWidgets.QPushButton(self.centralwidget)
        self.joinButton.setGeometry(QtCore.QRect(550, 160, 93, 28))
        self.joinButton.setObjectName("joinButton")
        self.leaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.leaveButton.setGeometry(QtCore.QRect(660, 160, 93, 28))
        self.leaveButton.setObjectName("leaveButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 250, 251, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 471, 391))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.disableButton = QtWidgets.QPushButton(self.centralwidget)
        self.disableButton.setGeometry(QtCore.QRect(650, 190, 130, 28))
        self.disableButton.setObjectName("disableButton")
        self.enableButton = QtWidgets.QPushButton(self.centralwidget)
        self.enableButton.setGeometry(QtCore.QRect(520, 190, 130, 28))
        self.enableButton.setObjectName("enableButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 40, 111, 16))
        font = QtGui.QFont()
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.appIdEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.appIdEdit.setGeometry(QtCore.QRect(540, 60, 231, 31))
        self.appIdEdit.setObjectName("appIdEdit")
        self.channelEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.channelEdit.setGeometry(QtCore.QRect(540, 120, 231, 31))
        self.channelEdit.setObjectName("channelEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("basic-one-to-one-video", "basic-one-to-one-video"))
        self.label.setText(_translate("MainWindow", "Channel Name:"))
        self.joinButton.setText(_translate("MainWindow", "join"))
        self.leaveButton.setText(_translate("MainWindow", "leave"))
        self.disableButton.setText(_translate("MainWindow", "disableLocalVideo"))
        self.enableButton.setText(_translate("MainWindow", "enableLocalVideo"))
        self.label_2.setText(_translate("MainWindow", "AppId:"))
